dist: xenial
language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
  # - 'pypy3'
script:
  - pip install .[dev]
  - coverage run --source flask_rest_jsonapi_next -m pytest -v
branches:
  only:
    - development
    - master
    - "/^feature.*$/"
after_success:
  - coveralls
